version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
#    build:
#      context: ./services/Gateway
#      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
    depends_on:
      - product-service
      - report-service
      - shop-service

  product-service:
    #image: danijelradakovic/consumer-service
    image: product-service
    build:
      context: ./AgentProductService
      dockerfile: Dockerfile
    ports:
      - 9000:8080
    networks:
      - backend

  report-service:
    #image: danijelradakovic/order-service
    image: report-service
    build:
      context: ./AgentReportService
      dockerfile: Dockerfile
    ports:
      - 9001:8080
    networks:
      - backend
    environment:
      PRODUCT_SERVICE_DOMAIN: ${PRODUCT_SERVICE_DOMAIN}
      PRODUCT_SERVICE_PORT: ${PRODUCT_SERVICE_PORT}
      SHOP_SERVICE_DOMAIN: ${SHOP_SERVICE_DOMAIN}
      SHOP_SERVICE_PORT: ${SHOP_SERVICE_PORT}

  shop-service:
    #image: danijelradakovic/kitchen-service
    image: shop-service
    build:
      context: ./AgentShopService
      dockerfile: Dockerfile
    ports:
      - 9002:8080
    networks:
      - backend
    environment:
      PRODUCT_SERVICE_DOMAIN: ${PRODUCT_SERVICE_DOMAIN}
      PRODUCT_SERVICE_PORT: ${PRODUCT_SERVICE_PORT}


networks:
  backend:
    name: agent-backend
    driver: bridge