server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: agent-shop-service
          uri: lb://agent-shop-service
          predicates:
            - Method=GET,POST
        - id: agent-product-service
          uri: lb://agent-product-service
          predicates:
            - Method=GET,POST
        - id: agent-report-service
          uri: lb://agent-report-service
          predicates:
            - Method=GET,POST
      # add routes here example :
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoint:
    service-registry:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 3
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
