server:
  port: 0

spring:
  application:
    name: agent-product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/agent
    username: root
    password: root
    data: classpath:dataDev.sql
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: Agent

hostAdress: localhost:8080
