server:
  port: 0

spring:
  application:
    name: agent-product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/agent
    username: root
    password: root
    data: classpath:dataDev.sql
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: Agent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    nonSecurePortEnabled: true
    securePortEnabled: false
    securePort: ${server.port}
